
# for using selenum grid
#execution_env=local
execution_env=remote
#**********************************
appURL= https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
gridURL = http://localhost/wd/hub
user_name = Admin
password = admin123